This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./out-ruco/2021-ruco-phd-thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file out-ruco/2021-ruco-phd-thesis.acn...done (0 entries accepted, 0 rejected).
Nothing written in out-ruco/2021-ruco-phd-thesis.acr.
Transcript written in out-ruco/2021-ruco-phd-thesis.alg.
